defaults:
  - pipeline

sweep:
  command_args: >
    --config-name=aa_ppi_ideal
    inference.ckpt_path=
      ${oc.env:RFDIFFUSION2_WEIGHTS_DIR}/ppi_robust_struct.pt
    transforms.configs.CenterPostTransform.center_type=hotspot
    inference.str_self_cond=False
    diffuser.T=50
    ++idealization_metric_n_steps=50
    +inference.conditions.per_res_plddt_pae_int_cond={}
    +inference.conditions.target_hbond_satisfaction_cond={}
  benchmark_json: ppi_rf_bench.json
  benchmarks: all
  num_per_condition: 1
  num_per_job: 1

in_proc: 1
start_step: sweep
stop_step: end

score:
  run: af2_initial_guess

metrics:
  sequence_metrics:
    - default
    - af2_initial_guess_metrics

outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_ppi_v1
