#!/bin/bash 

# Note 1: rf_diffusion needs to be accessible in your $PYTHONPATH
# Note 2: You will need to change the pdb path to some pdb you want to refine which was generated by ca rfdiffusion diffusion model

# Hint: Look at the config yaml!

output_pref="./experiments/out"

apptainer exec --nv ./exec/bakerlab_rf_diffusion_aa.sif python run_inference.py \
    --config-name="RFdiffusion_CA_inference" \
    inference.output_prefix=${output_pref} \
    inference.num_designs=30
