# Example config for running ppi examples with ideal_ss
defaults:
  - aa_ppi

inference:
  ckpt_path: ${oc.env:RFDIFFUSION2_WEIGHTS_DIR}/ppi_robust_struct.pt

upstream_inference_transforms: # These transforms don't do anything unless specific flags are set
  names:
    - HotspotAntihotspotResInferenceTransform
    - ExposedTerminusTransform
    - AutogenerateTargetSSADJTransform
    - LoadTargetSSADJTransform
    - RenumberCroppedInput
    - SSSprinkleTransform
    - ADJSprinkleTransform
    - AddIdealSSInferenceTransform
  configs:
    AddIdealSSInferenceTransform:
      only_first_chain: True



